### ISSUE TITLE
[Feature Request] Add support for Facebook too

### ISSUE THREAD

**Issue by o3661606** [Lisiadito/removeInstagramLoginEnforcement#1]
Any plan to add support for Facebook as well? Thanks!

**Comment by Lisiadito** [comment]
I can take a look. should be possible to get around the same way then on instagram

**Comment by Lisiadito** [comment]
Hey @o3661606 i created a seperated extension for facebook to keep things seperated. 
You'll find it [here](https://github.com/Lisiadito/removeFacebookLoginEnforcement)
