### ISSUE TITLE
Uncaught TypeError: Cannot read property 'value' of undefined

### ISSUE THREAD

**Issue by georgethemarmot** [Lisiadito/removeInstagramLoginEnforcement#2]
Hi, 
photo links are broken and in the extension error 
"Uncaught TypeError: Cannot read property 'value' of undefined" shows up 
Stack Trace
content.js:4 (anonymous function)

Consider taking a look at this code
https://github.com/hamada2029/instagram_without_login

**Comment by Lisiadito** [comment]
Thanks for reporting this issue. I will take a look. 
Can you describe when does this happen exactly? A screenshot might be helpful as well.

**Comment by Lisiadito** [comment]
Ok I checked and they changed the behavior of the website. I will see if I can get it fixed
