### ISSUE TITLE
public profile forces to login

### ISSUE THREAD

**Issue by lastnightmare** [Lisiadito/removeInstagramLoginEnforcement#8]
I just installed the chrome extension. While trying to visit a public profile, it forced me to login from the following link:

https://www.instagram.com/accounts/login/?next=/*/

It seems Instagram does not allow public profile visits anymore. The extension needs an update. Can you update the extension accordingly? Thanks.

**Comment by Lisiadito** [comment]
Will check it! Thanks for opening that issue.

**Comment by Lisiadito** [comment]
I can't reproduce the bug. 
Do you have the newest version of the extension installed? 
Do you use the extension in an incognito window?

I visited https://www.instagram.com/instagram/ and was able to scroll through it without problems.

**Comment by lastnightmare** [comment]
Version: 0.1.0 (master)
Allowed incognito but the issue persists in both modes.
Visiting [Instagram page](https://www.instagram.com/instagram/) results https://www.instagram.com/accounts/login/?next=/instagram/
Note that the issue is not related to login pop-up. It redirects to this link immediately.

**Comment by Lisiadito** [comment]
I failed a bit to raise the version number the last times I updated the plugin. Could you try to pull the repository again reload the plugin to see if that fixes the issue?

**Comment by lastnightmare** [comment]
Sure, but I already did that with master (7a9d06d). No changes.
I do not have an account, so I never signed in.
If there is a way I can help you to reproduce the bug, please tell me.

**Comment by Lisiadito** [comment]
I will see if I can try to reproduce this on another pc where I've never logged into instagram before.

**Comment by Phantomb** [comment]
I also have the same issue, just get redirected

**Comment by lastnightmare** [comment]
Issue is solved by itself. Probably Instagram changed its site behaviour. The extension works for clicking on image and scrolling down the page. I will re-open the issue if it happens again.
